version: '3'
services:
  best-hair-api:
    container_name: best-hair-api
    image: rolaxxx3/best-hair-api:latest
    ports:
      - '8087:3000'
    links:
      - best_hair_database
  best-hair-db:
    container_name: db-best-hair
    image: mongo
    ports:
      - '27017:27017'
    environment: 
      MONGO_INITDB_DATABASE: best-hair
  upstream:
    image: nginx
    restart: unless-stopped
    ports:
     - "8080:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
  webclient:
    container_name: web-best-hair
    image: rolaxxx3/best-hair-web:latest
    ports: 
      - '80:80'